#!/bin/bash
# Quick reference for deployment URLs and next steps

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║           NAO Medical - Deployment Status                     ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "✅ COMPLETED:"
echo "   • Frontend deployed to Vercel"
echo "   • Code pushed to GitHub"
echo "   • Deployment configs created"
echo ""
echo "🔗 FRONTEND URL:"
echo "   https://vite-project-pearl-zeta.vercel.app"
echo ""
echo "📋 NEXT STEPS (Manual - Render doesn't have CLI deployment):"
echo ""
echo "1️⃣  Create PostgreSQL Database on Render:"
echo "   → Go to: https://render.com/new/database"
echo "   → Name: nao-medical-db"
echo "   → Plan: Free"
echo "   → Copy the Internal Database URL"
echo ""
echo "2️⃣  Deploy Backend on Render:"
echo "   → Go to: https://render.com/new/web"
echo "   → Connect GitHub repo: shrey11184/nao-medical"
echo "   → Root Directory: backend"
echo "   → Build Command:"
echo "     pip install -r requirements.txt && prisma generate && prisma db push"
echo "   → Start Command:"
echo "     uvicorn app.main:app --host 0.0.0.0 --port \$PORT"
echo ""
echo "3️⃣  Add Environment Variables in Render:"
echo "   DATABASE_URL = [Your PostgreSQL URL from step 1]"
echo "   GEMINI_API_KEY = [Your Gemini API key]"
echo "   CORS_ORIGINS = https://vite-project-pearl-zeta.vercel.app"
echo "   PYTHON_VERSION = 3.11.0"
echo ""
echo "4️⃣  Update Vercel Environment Variable:"
echo "   → Go to: https://vercel.com/shreys-projects-3c62dc56/vite-project/settings"
echo "   → Add: VITE_API_URL = [Your Render backend URL]"
echo "   → Redeploy"
echo ""
echo "📚 Detailed Instructions:"
echo "   See RENDER_DEPLOY.md for step-by-step guide"
echo ""
echo "⏱️  Estimated Time: 15-20 minutes"
echo ""
